apiVersion: v1
kind: Template
metadata:
  name: generatejsonlog-template
objects:
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    name: log4j2
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        annotations:
          capabilities: Seamless Upgrades
          containerImage: docker.io/qiaolingtang/generate-log:latest
          support: Qiaoling Tang
        creationTimestamp: null
        labels:
          name: log4j2
      spec:
        containers:
        - args:
          - /run.sh
          command:
          - /bin/sh
          image: docker.io/qiaolingtang/generate-log:latest
          imagePullPolicy: IfNotPresent
          name: log4j2
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
